- name: Add Docker GPG APT key
apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
    apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Update APT and install docker-ce
    apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
with_items:
    - docker-ce
    - docker-ce-cli
    - docker-compose
    - containerd.io